mozilla/mozregression

mozregression/bisector.py, mozregression/build_data.py, mozregression/errors.py, mozregression/launchers.py, mozregression/main.py, mozregression/test_runner.py, mozregression/utils.py, tests/unit/test_bisector.py, tests/unit/test_build_data.py, tests/unit/test_launchers.py, tests/unit/test_test_runner.py, tests/unit/test_utils.py
This address the following bug: https://bugzilla.mozilla.org/show_bug.cgi?id=1120068
=> Fix nightly build txt regression

mozregression/errors.py, mozregression/main.py, mozregression/utils.py, tests/unit/test_main.py, tests/unit/test_utils.py
This also address https://bugzilla.mozilla.org/show_bug.cgi?id=1124836.
=> Refactor main module

index.md
=> Update index.md to fix 'can works with'

mozregression/test_runner.py, tests/unit/test_test_runner.py
This address issue https://bugzilla.mozilla.org/show_bug.cgi?id=1002387
=> keep the downloaded files in manual bisection even when persist is None

mozregression/utils.py, tests/unit/test_fetch_configs.py, tests/unit/test_utils.py
See https://bugzilla.mozilla.org/show_bug.cgi?id=1130365.
=>  handle the new win64 nightly builds file naming scheme

mozregression/launchers.py, setup.py, tests/unit/test_launchers.py
Do not merge yet - waiting for mozversion release
=> use the package_name info from mozversion to start fennec

mozregression/launchers.py
https://bugzilla.mozilla.org/show_bug.cgi?id=1134820
=>  	Log the location of the executable we're launching … 

mozregression/bisector.py, mozregression/main.py, tests/unit/test_main.py
See https://bugzilla.mozilla.org/show_bug.cgi?id=1048858.
=> print pushlogurl on keyboard interrupt exit

tests/unit/test_main.py
=> Tests added for Function main.preference

tests/unit/test_main.py
It would be better to have some unit tests for the function 'check_mozregression_version' in mozregression.main.py. Thats why I wrote these functions
=> Unit tests for the function 'check_mozregression_version' in mozregression.main.py

.travis.yml, appveyor.yml, gui/build.py, gui/mozregui/bisection.py, gui/tests/__init__.py, gui/tests/test_bisection.py
Do not merge this yet - under testing.
=> run gui tests on travis/appveyor

gui/mozregui/wizard.py
fix the  issue of default to a one year regression range instead of year 2000  <a href = https://bugzilla.mozilla.org/show_bug.cgi?id=1156940]>(Bug 115690)</a>
=> fix the default status of 01/01/2000

gui/mozregui/wizard.py
Add the error check before user submit.
=> error checking for the regression range

gui/mozregui/report.py, gui/mozregui/ui/intro.ui, gui/mozregui/wizard.py
Hello, I think that I have added the QComboBox for inputting the "bits" of the application from the user. It seems to be working fine as when I choose "32", it downloads the corresponding "i686" version and when I choose "64" bits, it downloads the corresponding "x86_64" version.
=> Added QComboBox for inputting the bits from the user

gui/mozregui/wizard.py
Added a single line that makes the default application to be selected "firefox"
=> The default application is now 'firefox'

gui/mozregui/bisection.py, gui/mozregui/wizard.py
Hmm, I hope it may works this time:)
=> fix bug 1158125

mozregression/utils.py
See https://bugzilla.mozilla.org/show_bug.cgi?id=1128240
=> update latest firefox release dates

gui/mozregui/report.py
good = green
bad = red
skip = yellow
retry = gray
no verdict = light gray
=> Add colors into report view representing verdicts

gui/mozregui/ui/mainwindow.ui
Add views menu which permits to hide/show the toolbar and the log view  + disable default context menu on right click on toolbar and main widget.
=> Bug 1173982 - Add views menu which permits to hide/show the toolbar and the log view

_posts/2015-06-07-0.37-release.md, documentation/configuration.md, documentation/usage.md
Do not merge this yet!
Some documentation for the future mozregression 0.37 release.
=> Release 0.37

gui/mozregui/ui/inbound.ui, gui/mozregui/wizard.py
Hm, some ssl warning and 404 not found error shows up when I search for "b2g-inbound". But I do believe I just do the same thing with nightly. Could you test it on your local environment? I will figure out the problem If same error shows up. Thank you very much! @parkouss
=> Bug 1179229 - [gui] allow to choose the inbound branch using the wizard

_posts/2015-08-12-0.41-release.md
@wlach could you review this please ?
=> add post for the 0.41 release

mozregression/bisector.py, mozregression/build_info.py, mozregression/download_manager.py, mozregression/main.py, tests/unit/test_build_data.py, tests/unit/test_build_info.py, tests/unit/test_download_manager.py
See https://bugzilla.mozilla.org/show_bug.cgi?id=1160078.
=> Bug 1160078 - With --persist, prioritize already downloaded builds over builds which require a download

mozregression/cli.py, mozregression/main.py, tests/unit/test_bisector.py, tests/unit/test_cli.py, tests/unit/test_main.py
- Created cli module and its associated test_cli.py unittests
- Move args parser from main to cli module
- Moved args parser (which now concerns only defaults handling) tests from  test_main.py to test_cli.py
- Fix preexisting typo
=> 1195082 main split

mozregression/cli.py, mozregression/config.py, mozregression/launchers.py, tests/unit/test_cli.py
This is based on other work - DO NOT MERGE as it is.
=> Mozversion logging

gui/mozregui/bisection.py, mozregression/bisector.py, mozregression/branches.py, mozregression/cli.py, mozregression/fetch_build_info.py, mozregression/fetch_configs.py, mozregression/json_pushes.py, mozregression/main.py, tests/unit/test_branches.py, tests/unit/test_build_range.py, tests/unit/test_fetch_configs.py, tests/unit/test_main.py
See https://parkouss.wordpress.com/2015/11/14/mozregression-new-way-for-handling-merges/
=> Handling merge commits

mozregression/bisector.py
This patch allow to reduce the required launch time by looking
for next builds to download in a thread, in parallel with the
installation and test steps of the build.
=> Bug 1216232 - reduce build launch time

gui/mozregui/bisection.py, gui/mozregui/build_runner.py, gui/mozregui/global_prefs.py, gui/mozregui/ui/global_prefs.ui
Add the ability to download background builds (now the default)
and a global pref to change that.
=> [GUI] download background builds

documentation/usage.md
And remove documentation for the no-background-dl - this is an advanced
usage option.
=> Document the profile-persistence option

mozregression/branches.py, mozregression/fetch_build_info.py, mozregression/fetch_configs.py
Add try branch support: https://bugzilla.mozilla.org/show_bug.cgi?id=1240033.
=> Try support

gui/mozregui/bisection.py
We calculate the middle of the build range to know which build should be
run.
In case a retry is done after a skip, this lead to an error - so for the
retry action we should not calculate the middle again, just reuse the
previous one.
I took the opportunity to clean the mid/self.mid redundancy in the code.
=> Bug 1245333 - [gui] wrong build for retry

mozregression/launchers.py
On windows, if a firefox build is stopped after it had restarted (from
Menu (≡) -> [?] -> Restart with Add-ons Disabled for example) it will
hang for a couple of minutes.
The blocking comes from mozprocess, but it is quite hard to fix properly,
and it is a corner case - so here is a workaround patch.
It run the stop method in a thread, and wait 0.7 seconds for its
completion. If the thread is not terminated after that, we simply forget
it, so it will be finished later (abruptly in case the program ends
before the completion).
=> Bug 1245332 - stopping firefox may hang on windows

mozregression/bisector.py
Try to automatically bisect on inbounds when we don't have enough
information to know where a merge comes from.
=> Bug 1254804 - mozregression doesn't properly visit inbound builds

check.py, mozregression/bisector.py
@wlach Does this seem better? I chose 100 as a reasonable slightly longer length (default is 79).
=> Allow longer line lengths

mozregression/main.py
We weren't checking that there wasn't any pushes between the good/bad
results in inbound bisection, which would cast doubt that the first
found "bad" push really was the bad one.
=> Bug 1334669 - Don't show bug numbers if >1 push that could be bad

mozregression/cli.py
@wlach minor change, can you help to see this? thanks.
=> wrong syntax for string formatting

mozregression/launchers.py
This should disable the updater and telemetry
=> Make fennec use the firefox profile

mozregression/bisector.py
get_category will return "default" or "try" which will never meet the condition.
Replace by "get_name" and let branch finding continues.
=> Bug 1350065 - Bisect autoland builds

requirements-gui-dev.txt, setup.py
Fixes: https://bugzilla.mozilla.org/show_bug.cgi?id=1375832
=> Use requests[security], pinned to 2.15.1

mozregression/main.py
=> typo in main.py

mozregression/releases.py
Seeing as creating a new mozregression manually for each new Firefox version seemed a bit tedious I thought I'd give this a go, looking for some feedback @wlach .
(Don't need to delete as many/any of the existing dates that I have, but I wanted to test it with some different version numbers)
Apologies if some of this isn't particularly idiomatic python.
I'm also not sure if the date handling will do the right thing when run in other timezones, but it might not be a huge deal if it downloads a version one day out.
=> Bug 1128240 - Fetch merge dates for Firefox versions from hg tags.

mozregression/bisector.py
https://bugzilla.mozilla.org/show_bug.cgi?id=1464937
=> Refactor and fix up logic to find last known good changeset when changing branches from a merge.

setup.py
https://bugzilla.mozilla.org/show_bug.cgi?id=1533517
=> Use mozdevice 3.0.1

mozregression/fetch_configs.py, mozregression/launchers.py, tests/unit/test_cli.py, tests/unit/test_fetch_configs.py
- Disable app auto update when launching Thunderbird
- Support CI bisection of Thunderbird
=> Improve Thunderbird support

gui/mozregui/bisection.py, gui/mozregui/build_runner.py, gui/mozregui/report.py, gui/mozregui/single_runner.py, mozregression/bisector.py, mozregression/build_info.py, mozregression/build_range.py, mozregression/cli.py, mozregression/config.py, mozregression/fetch_build_info.py, mozregression/fetch_configs.py, mozregression/json_pushes.py, mozregression/main.py, tests/unit/test_approx_persist.py, tests/unit/test_bisector.py, tests/unit/test_build_info.py, tests/unit/test_build_range.py, tests/unit/test_cli.py, tests/unit/test_fetch_build_info.py, tests/unit/test_fetch_configs.py, tests/unit/test_json_pushes.py, tests/unit/test_main.py
We should begin by bisecting on mozilla-central, not autoland
=> Bug 1612627 - Fix bisection of geckoview example app

setup.py
=> Remove code to run tests from setup.py

appveyor.yml
It actually makes mozregression non-runnable :(
=> Revert virtualenv on appveyor

gui/build.py, gui/gui.spec, gui/mozregui/ui/mainwindow.ui, gui/wininst/wininst.nsi
* mozregression-gui -> mozregression GUI on Mac
* fix a bug in Windows packaging
* fix retina mode on Mac
=> A few more build tweaks for the GUI

mozregression/fetch_configs.py
I haven't formally tested this yet, but will be needed once the stack on https://bugzilla.mozilla.org/show_bug.cgi?id=1614970 lands, I'll comment here when that happens.
=> Bug 1638073 - Support android shippable index's

mozregression/approx_persist.py, mozregression/bisector.py, mozregression/branches.py, mozregression/build_info.py, mozregression/build_range.py, mozregression/class_registry.py, mozregression/config.py, mozregression/fetch_configs.py, mozregression/json_pushes.py, mozregression/launchers.py, mozregression/log.py, mozregression/network.py, mozregression/releases.py, mozregression/tempdir.py, mozregression/test_runner.py, requirements/base.in, setup.py, tests/unit/test_bisector.py, tests/unit/test_build_range.py, tests/unit/test_cli.py, tests/unit/test_main.py, tests/unit/test_test_runner.py
We don't support python2 anymore so six is no longer needed.
=> Stop using six

.travis.yml
This will let us measure the effect of any changes
=> Bug 1645860 - Print size of generated gui bundles on Linux and Mac

README.md, docs/quickstart.md, gui/mozregui/mainwindow.py, gui/mozregui/ui/intro.ui, gui/wininst/wininst.nsi, mozregression/cli.py
Opened the about window and saw it and it bugged me.
=> Remove a few more uses of inbound in user-visible text

gui/mozregui/bisection.py, gui/mozregui/build_runner.py, gui/mozregui/ui/intro.ui, gui/mozregui/wizard.py, mozregression/cli.py, mozregression/fetch_build_info.py, mozregression/fetch_configs.py, mozregression/main.py, mozregression/network.py, tests/unit/test_fetch_build_info.py, tests/unit/test_fetch_configs.py, tests/unit/test_network.py
This is a bit hacky, but gets the job done, and I think a less-hacky way would involve a greater re-factoring than I am willing or able to attempt.
=> Bug 1401649 - Add support for bisect l10n nightly builds

mozregression/network.py
e.g. requests.exceptions.ReadTimeout
=> Retry on Timeout exceptions too

.github/workflows/build.yml
It seems like the easiest way to do this is just with CURL.
=> Upload release assets

.github/workflows/build.yml
Using this solution https://github.com/lemurheavy/coveralls-public/issues/1435#issuecomment-823508409
=> Hopefully fix coveralls

.github/workflows/build.yml
This is a really weird problem, maybe setting the token for the job (instead of just the step) will help?
=> Attempt to fix up setting of coveralls tokens

.github/workflows/build.yml
https://github.com/TheKevJames/coveralls-python/issues/252
=> Another attempt at fixing coveralls

requirements/requirements-3.7-Linux.txt, requirements/requirements-3.8-Linux.txt, requirements/requirements-3.9-Linux.txt, requirements/requirements-3.9-Windows.txt, requirements/requirements-3.9-macOS.txt
- upgrade jsonschema to 4.7.1
- upgrade pyinstaller-hooks-contrib to 2022.8
=> requirements: update various packages

docs/documentation/usage.md
Add some instructions to usage.md to explain how to set prefs.
Also add examples pref files for the --preferences argument
=> documentation: document the arguments that set prefs

requirements/requirements-3.10-Linux.txt, requirements/requirements-3.10-Windows.txt, requirements/requirements-3.10-macOS.txt, requirements/requirements-3.7-Linux.txt, requirements/requirements-3.8-Linux.txt, requirements/requirements-3.9-Linux.txt, requirements/requirements-3.9-Windows.txt, requirements/requirements-3.9-macOS.txt
Update:
- distro from 1.7.0 to 1.8.0
- glean-parser from 6.2.0 to 6.2.1
- setuptools from 65.4.1 to 65.5.0
=> requirements: upgrade various packages

.github/workflows/deploy-gui.yml, docs/install.md
- add build on Ubuntu 22.04
- update documentation to reflect new builds
- rename archives in releases to reflect new builds
=> workflows: add ubuntu-22.04 builds (bug 1796149)

requirements/base.in, requirements/requirements-3.10-Linux.txt, requirements/requirements-3.10-Windows.txt, requirements/requirements-3.10-macOS.txt, requirements/requirements-3.11-Linux.txt, requirements/requirements-3.11-Windows.txt, requirements/requirements-3.11-macOS.txt, requirements/requirements-3.7-Linux.txt, requirements/requirements-3.8-Linux.txt, requirements/requirements-3.9-Linux.txt, requirements/requirements-3.9-Windows.txt, requirements/requirements-3.9-macOS.txt
urllib3 upgraded from 1.26.15 to 2.0.2
mypy-extensions upgraded from 0.4.3 to 1.0.0
glean-sdk upgraded from 52.6.0 to 52.7.0
=> requirements: upgrade various requirements

gui/build.py, gui/dmg_settings.py, requirements/base.in, requirements/requirements-3.10-Linux.txt, requirements/requirements-3.10-Windows.txt, requirements/requirements-3.10-macOS.txt, requirements/requirements-3.11-Linux.txt, requirements/requirements-3.11-Windows.txt, requirements/requirements-3.11-macOS.txt, requirements/requirements-3.7-Linux.txt, requirements/requirements-3.8-Linux.txt, requirements/requirements-3.9-Linux.txt, requirements/requirements-3.9-Windows.txt, requirements/requirements-3.9-macOS.txt
- add dmgbuild to requirements
- add dmg_settings.py
- update build scripts
=> build: add Applications link + arrow to fancy dmg (bug 1836791)

.github/workflows/build.yml, .github/workflows/deploy-gui.yml, .gitignore, README.md, bin/adhoc-sign.py, bin/dmgbuild, gui/build.py, gui/mac/entitlements.xml, gui/mac/requirements.plist
- add entitlements/requirements files for codesign
- add app bundle to gzipped tarball
- add script to generate manifest
- add script to generate dmg package
=> gui: package signing changes (bug 1810744)

gui/mac/entitlements.xml
See [bug 1845375](https://bugzilla.mozilla.org/show_bug.cgi?id=1845375).
=> gui: update macOS entitlements (bug 1845375)

.github/workflows/deploy-gui.yml, bin/adhoc-sign.py, gui/build.py
- update adhoc-sign script to support windows installer
- rename unsigned installer binary
- add workflow step to print manifest
=> build: add support for windows adhoc signing (bug 1839227)

gui/gui.spec, gui/splash_hook.py, mozregression/pyinstaller.py
- create new BUNDLE_WITH_TK class
- add required tcl/tk files to "lib" directory in bundle
- force resigning of bundle after it is assembled
- add splash runtime hook that shows a loading message
=> gui: add splash screen hook (bug 1845573)

.github/workflows/build.yml, .github/workflows/compile-requirements.yml, .github/workflows/deploy-gui.yml, .github/workflows/deploy.yml, .github/workflows/upload-gui-to-workflow.yml
- update actions/setup-python from v2, v4 to v5                                                                                                                                                                                             
- update actions/upload-artifact from v2, v3 to v4
- update actions/checkout from v2, v3 to v4
- update actions/download-artifact from v3 to v4
=> workflows: update various GitHub Actions (bug 1917091)

.github/workflows/deploy-gui.yml, .github/workflows/upload-gui-to-workflow.yml
- remove ubuntu 20.04
- add ubuntu 24.04
=> workflows: update ubuntu image for gui build (bug 1982049)
