mozilla/mozregression

.travis.yml, mozregression/bisector.py, mozregression/build_data.py, mozregression/errors.py, mozregression/fetch_configs.py, mozregression/limitedfilecache.py, mozregression/main.py, mozregression/utils.py, setup.py, tests/unit/test_bisector.py, tests/unit/test_build_data.py, tests/unit/test_fetch_configs.py, tests/unit/test_launchers.py, tests/unit/test_main.py, tests/unit/test_test_runner.py, tests/unit/test_utils.py
Hi guys,
(This is my first bug)
Just finished working on the [pep8 check for travis ci build on mozregression](https://bugzilla.mozilla.org/show_bug.cgi?id=1127575) feature. While making the code PEP-8 compliant I was not exactly focussing on the neatest solution, but more the quickest one, If considered a good idea I will open an issue about neatening up the whole project (if there is not already one).
=> "pep8 check for travis ci build on mozregression"

mozregression/main.py, tests/unit/test_bisector.py, tests/unit/test_main.py
mozregression try to load a configuration file located on
"~/mozregression.cfg" and takes its values as default values
(overridable by command line passed args).
=> Bug 1111310 - Allow to configure mozregression with config file(s)

.gitignore, mozregression/bisector.py, mozregression/main.py, tests/unit/test_bisector.py, tests/unit/test_main.py
As suggested by @wlach We want to bisect inbound if last good revision and first bad revision are set, so I added a condition for this. Let me know if this is the correct way to implement it.
=> #Bug 1106804 - --inbound-branch should imply --inbound

mozregression/main.py
Added the code that checks for a new version of Mozregression when Mozrgression is started from the terminal/command prompt.
(Asking users for a upgrade might be beneficial in this case as better version of mozregression might be having improved features
that the user can use for finding out the regression range in the corresponding mozilla products)
If a new version of Mozregression is out on PyPI, then Mozregression informs the
user about it and suggests the user to upgrade to the new version by issuing one
of the two commands:
1) pip install -U mozregression
2) pip install --upgrade mozregression
If the user already has the latest version, then Mozregression continues as usual.
=> Mozregression may ask user for upgrade

mozregression/bisector.py, mozregression/build_data.py, tests/unit/test_build_data.py
Sometimes when looking for next builds to download the build data
cache is modified because a build is not valid. This patch handle
this corner case by clearing the cache and returning the new valid
mid point that we are testing.
=> fix a download background issue when build data cache changes

gui/mozregui/wizard.py, mozregression/fetch_configs.py
Added the following changes:
1) Only 32-bits is presented to the user in the drop down menu
if the user uses a 32 bit OS (as a 32 bit OS can't run a 64-
bit application), otherwise both the options are shown.
2) Hiding the bits field when the application is 'fennec' or
fennec-2.3'. The fennec application can only run on a
connected android device- so we don't care about the bits here.
=> Bug/1159728 [gui] limit the choices for the bits fields

_layouts/home.html, _posts/2015-05-11-gui.md, index.md, install.md
To see how this will looks: http://parkouss.github.io/mozregression/
=> post for the alpha mozregression-gui release

gui/mozregui/bisection.py, gui/mozregui/main.py
When quitting mozgui after an app downloading for a bisection, when
persist is not defined by the user, the temp dir persists.
To fix this behaviour, we now create a temp_dir specific for the
mainwindow and pass it to the Bisector class.
Then on close, we explicly delete it.
=> Fix bug 1165434, use a global temp dir when no persists defined

setup.py
I've made a patch for cachecontrol to easily track dependencies when using the local file cache (as we do):
https://github.com/ionrock/cachecontrol/commit/57dddb23ff220e4bac2df5ad5ff5df8304098ff5
This has now been released, so we should use it (this is called extra dependencies for pip).
@wlach @jpigree  r?
=> use the filecache extra dependency with cachecontrol

gui/mozregui/main.py, gui/mozregui/ui/mainwindow.ui
- On mainwindow init, synchronize checkbox of menuViews actions with
actual visibility
- Add slot on visibility change to update the menuViews actions checkbox state
Not necessary on actionToolbar since the toolbar can't be hide manually but I kept the code in case we reactivate it.
=> Fix menuViews desynchro

setup.py
This allow us to run our mozregression unit tests using py.test.
Mostly taken from https://pytest.org/latest/goodpractises.html#integration-with-setuptools-test-commands.
@jpigree what do you think of it ?
This is just a simple wrapper around the "python setup.py test" command that run unit tests for mozregression - now tests will run using pytest, so new tests can be written using that lib. This make sense to me as we are now using pytest for our gui tests.
=> run mozregression unittests using pytest

gui/mozregui/log_report.py
Now, thing is like this.
We got two kinds of methods to make our level message more obvious. And we do need to choose one from them to make log view more friendly. So I will paste them blow and please give me some feedback before I finish this patch.
@jpigree @parkouss please tell me which one you prefer, or you have a better ideal about the color of level message. Thank you very much! :)
=> Bug 1173981 - [gui] add colors for the log levels

mozregression/bisector.py, mozregression/download_manager.py, mozregression/main.py, tests/unit/test_download_manager.py
This add a new command line option '--background-dl-policy' that can be filled
with two values:
- 'cancel' (the default) cancel any background build as soon as we know
which build the user need
- 'keep' this do not stop background downloads, so every file downloaded
(even non tested) is kept in the persist folder if any.
=> add the ability to keep downloading files in background

gui/build.py, gui/mozregui/global_prefs.py, gui/mozregui/main.py, gui/mozregui/patch_requests.py
This fixes the bundled (ie frozen) version of mozregression gui.
Two fixes:
- include a taskcluster package required file that was not bundled
- requests requires a cacert.pem file that taskcluster (and mozregression also) now uses.
=> Taskcluster gui bundle

mozregression/utils.py, tests/unit/test_utils.py
This allow to exit cleanly with a nice error message instead
of a full stack trace that is hard to understand.
=> raise MozregressionError if os is unknown or unsupported

mozregression/launchers.py, tests/unit/test_launchers.py
* When using an existing mozprofile, mozregression modifies it without
reverting the changes after the tests. This fix makes it clone the
existing profile in order to preserve its state.
* This fix needs mozprofile >= 0.24 in order to clean up the profile
created into the tmp directory when no reference to the object is left.
=> Fortunately, setup.py is already updated to 0.25 so no change needed.
* Adapted launcher unit tests accordingly.
* Factorized multiple hard coded strings into launcher test cases.
=> Clone existing mozprofiles to prevent persistence

tests/unit/test_bisector.py, tests/unit/test_launchers.py
Okay. As I said in the issue, it seems that py.tests does not execute the __del__ methods. So I add to explicitly call them (addCleanUp).
=> 1191254 empty directories

mozregression/bisector.py, mozregression/errors.py, mozregression/launchers.py, mozregression/test_runner.py, tests/unit/test_bisector.py, tests/unit/test_launchers.py, tests/unit/test_test_runner.py
This handle cases when we got some exception while:
1. trying to install the application
2. trying to start the application
3. trying to stop the application.
For cases 1 and 2, this is an "uncoverable" error. So the raw
exception is printed, and we force skipping the build.
Case 3 can be recovered, so the only thing we do is print the raw
error, but we keep the verdict that the user entered and the
app_info dict extracted from the installed application.
=> Bug 1192485 - handle errors when running the tested application

setup.py
=> Bug 1185787 - Unable to bisect on preview releases of Android

gui/mozregui/pref_editor.py
This is a fix for Bug 1224083 - https://bugzilla.mozilla.org/show_bug.cgi?id=1224083 .
On line 39, the new_value object was a QVariant object, which can be converted to a QString.
Using QString's __str__( ) method seems to have solved the issue.
=> Fix Unicode display and edit

mozregression/bisector.py, mozregression/build_info.py, mozregression/build_range.py, mozregression/cli.py, mozregression/dates.py, mozregression/fetch_configs.py, mozregression/test_runner.py, tests/unit/test_build_info.py, tests/unit/test_build_range.py, tests/unit/test_cli.py, tests/unit/test_fetch_configs.py, tests/unit/test_test_runner.py
This allow in --good-date, --bad-date, --launch to use a given buildid.
It works for nightlies only, as finding the buildid relies on the folder
name in archives.m.o.
A known bug is that files are stored using the build id, so it is
possible to have two files downloaded and kept in the persist dir
that are identical, example:
2015-11-03-03-02-48--mozilla-central--firefox-45.0a1.en-US.linux-x86_64.tar.bz2
2015-11-03--mozilla-central--firefox-45.0a1.en-US.linux-x86_64.tar.bz2
=> Bug 1217906 - allow to find build using build ids

mozregression/cli.py, tests/unit/test_cli.py
Basically use taskcluster when any specific build flavor is
asked (!= 'opt'). This allow the command
|mozregression -g 2015-11-20 -b 2015-11-22 -B debug| to work as expected.
=> Bug 1225544 - make use of the build flavor options for nightlies

mozregression/build_range.py, mozregression/cli.py, mozregression/json_pushes.py, mozregression/main.py, tests/unit/test_build_range.py, tests/unit/test_cli.py, tests/unit/test_main.py
Removes --good-release, --bad-release, --good-rev, --bad-rev and allow
--good and --bad to take any kind of range limit (a date, build id,
release number or changeset). Same possible values as for the --launch option.
=> Bug 1228951 - only use --good/--bad parameters

mozregression/download_manager.py, mozregression/main.py
Ensure that we don't have a race condition when the download_dir is
removed by first waiting for download threads to be finished.
=> Bug 1231745 - fix race condition when removing dl dir

gui/mozregui/bisection.py
We were calling self.finished twice, with the side effect of removing
the last step.
The else clause is removed so we still show the 'bisection is done'
dialog.
=> Bug 1232261 - [gui] do not delete last tested build

gui/mozregui/report.py
Removed the unnecessary setStyleSheet() call
=> [gui] Bisection Informations context menu text turns white when hovered

gui/mozregui/global_prefs.py, gui/mozregui/ui/global_prefs.ui
Added a 'Show Advanced Options' button in the global preferences dialog. Initially, `http timeout` and `background downloads` options are hidden. On clicking the button, the button's text changes to 'Hide Advanced Options' and the advanced options become visible.
=> Bug1234603 - [gui] Added Show/Hide Advanced Options button in global prefs dialog

mozregression/launchers.py, tests/unit/test_launchers.py
Fixes an uncaught exception when running Fennec:
```
$ mozregression --app fennec --launch 2015-10-29
0:01.10 LOG: MainThread download INFO Using local file: /home/mbrubeck/.mozilla/mozregression/persist/2015-10-29--mozilla-central--fennec-45.0a1.multi.android-arm.apk
0:01.10 LOG: MainThread Test Runner INFO Running mozilla-central build for 2015-10-29
0:01.15 LOG: MainThread mozversion INFO application_buildid: 20151029045227
0:01.15 LOG: MainThread mozversion INFO application_changeset: acb3f4ac5424181d3d4d73283668162137918cf1
0:01.15 LOG: MainThread mozversion INFO application_name: Fennec
0:01.15 LOG: MainThread mozversion INFO application_repository: https://hg.mozilla.org/mozilla-central
0:01.15 LOG: MainThread mozversion INFO application_version: 45.0a1
0:01.15 LOG: MainThread …
```
=> Pass package name to ADBAndroid.process_exist

gui/mozregui/ui/mainwindow.ui
Changed toggled() to triggered() to fix the disappearing QDockWidget
=> Bugfix #1219887 - actionLogView disappears on minmizing

gui/mozregui/report.py, mozregression/bisector.py
Old builds do not have enough metadata to print the pushlog url before
they are installed. This pat handle the case, and update the metadata as
soon as we have it.
=> Bug 1239993 - [gui] Do not crash when the pushlog is not available

gui/mozregui/build_runner.py, gui/tests/test_build_runner.py
This fix a bug that prevented a build to be launched after user cancellation.
=> Bug 1240393 - [gui] Mozregression can't restart a build

mozregression/fetch_configs.py, tests/unit/test_fetch_configs.py
For both archives.m.o and taskcluster, fennec route names have changed since
around 2016-01-29 - and mozregression can't find recent builds because
of that.
This patch should solve the issue by using api-15 instead of api-11
after this date.
=> Bug 1245335 - use android-api-15 for recent fennec builds

_includes/header.html
Will fix a mixed-content warning when the page is viewed over https.
=> Make the GitHub "Fork Me" ribbon http(s) agnostic

mozregression/cli.py
If you use mozregression with a "good" date that's newer than the "bad" date, it asks you:
> Maybe you wanted to use the --find-fix flag ?
Note the awkward space character at the end of the sentence there, before the question mark.  This pull request just drops that stray space.
=> drop stray space before question mark

setup.py
Work around mozdevice 0.48 requiring rooted devices by using the older version. https://bugzilla.mozilla.org/show_bug.cgi?id=1245347
=> Use mozdevice 0.47 only

mozregression/bisector.py
This allows a bisection to take place without using a download manager.
This is particularly useful bisecting builds where the data we're
interested in is already in test logs, so no binary is necessary.
My use case was to create a custom TestRunner that greps through logs looking for a specific warning. I use `mozregression.bisector.Bisector` to drive the bisection and let the TestRunner take care of downloading.
@parkouss What do you think?
=> Allow for a bisection without a download manager

mozregression/fetch_build_info.py, mozregression/fetch_configs.py, tests/unit/test_fetch_configs.py
Taskcluster routes (for linux64 debug at least) have temporarily changed
from using 'debug' to 'dbg'. Eventually this behavior will revert but
for now we need to special case it.
Additionally the binary archive name for builds in taskcluster has
changed from specifying the platform and architecture to just using a
generic term, 'target', for all platforms. The build regex has been
updated to handle that behavior.
=> Bug 1278683 - Update config and build info handling

mozregression/bisector.py
This updates the merge handling logic to choose the proper integration
branch when there is no merge commit message. Each integration branch is
queried for the changeset in question and the one containing it with the
earliest push date is chosen.
=> Bug 1304213 - Improve integration branch detection

mozregression/bisector.py
I tried to do a bisect in mozregression recently and it failed with **TypeError: unsupported operand type(s) for -: 'datetime.date' and 'datetime.datetime'**. It traces back to [`_print_progress` in bisector](https://github.com/mozilla/mozregression/blob/1e38c1e/mozregression/bisector.py#L157):
~~~python
def _print_progress(self, new_data):
next_good_date = new_data[0].build_date
next_bad_date = new_data[-1].build_date
next_days_range = abs((next_bad_date - next_good_date).days)
~~~
~~~
next_good_date: 2016-07-30 03:02:04       <--- this is a datetime
next_bad_date:  2016-08-27                <--- this is a date
~~~
It appears that Python does not allow getting the delta of a date and a datetime. To fix this I am proposing a change that converts both to datetimes, as well as a similar fix …
=> Fix bisect progress type mismatch, convert dates to datetimes

mozregression/fetch_configs.py, requirements-dev.txt
Later versions seem to be detecting new "problems" which we may
want to fix at some point, but not now.
=> Downgrade flake8 to version 2.5.4 and peg various python linting requirements

mozregression/fetch_configs.py
taskcluster changed artifact name so we can't match build file and download it.
I actually don't know which build info file (there're two, target.txt, target_info.txt) is correct.  please help to clarify, thank.
=> Bug 1334815 - Bisecting Fennec with taskcluster builds fails

.travis.yml
The build doesn't seem to work anymore (some kind of pyqt problem) but
it's not a configuration we're shipping in any case.
=> Stop testing GUI with OSX for now

mozregression/main.py, tests/unit/test_main.py
The "oh noes" message was cute, but it makes it seem as if something
went wrong during normal operation.
=> Use a more neutral message when inbound bisection is finished

mozregression/bisector.py, tests/unit/test_bisector.py
There may be less builds than actual revisions if some of the builds were bad,
see e.g. https://bugzilla.mozilla.org/show_bug.cgi?id=1384136
=> Change inbound progress message to talk about "builds" instead of "revisions"

mozregression/launchers.py, mozregression/main.py, mozregression/tempdir.py
If they aren't, we have sandboxing problems: https://bugzilla.mozilla.org/show_bug.cgi?id=1385928
=> Make sure long temporary path names are not shortened inside mozregression

mozregression/fetch_configs.py, tests/unit/test_fetch_configs.py
I hope I've picked the right timestamp for `TIMESTAMP_FENNEC_API_16` - I've used the date of [the first mozilla-central push](https://treeherder.mozilla.org/#/jobs?repo=mozilla-central&revision=d814f791de3bba0fce843614b41ca9696ce57b15&filter-searchStr=android%20(b)) that showed api-16 jobs on Treeherder.
=> Handle Fennec's switch to android-api-16 builds

mozregression/cli.py
This is a fix for https://bugzilla.mozilla.org/show_bug.cgi?id=1408439.
It will help in cases like https://github.com/mozilla/geckodriver/issues/972#issuecomment-336484921 when we mixup in how the variable has to be specified.
=> Display usage of variables in --command argument

mozregression/config.py
Right now the message about default build type (64-bit vs. 32-bit) incorrectly refers to them as "64 bits" and "32 bits".  The correct/common adjective for these types of builds are "64-bit" vs. "32-bit" (singular bits, and with a hyphen).  See e.g. https://support.mozilla.org/en-US/kb/switch-32-bit-64-bit as one reference on this language.
=> Fix typo in message about 64-bit systems

mozregression/launchers.py
Should cover https://bugzilla.mozilla.org/show_bug.cgi?id=1414879
Feedback is appreciated in case something's wrong.
=> Bug 1414879 - Avoid privacy notice on every launch

tests/unit/test_main.py
=> typo in test_main.py (followup of typo in main.py)

mozregression/bisector.py
Call _reverse_if_find_fix() when there is no explicit branch in commit message,
so find fix runs can continue onto integration branches.
=> Bug 1426105 - Make elimination branch detection work with find fix runs.

mozregression/bisector.py, mozregression/branches.py, tests/unit/test_branches.py
Some merge commit messages have the positions of the originating and target repos reversed.  This breaks mozregression's branch detection since it assumes the originating repo is always in the first position.  If the first repo is "mozilla-central" assume this is a transposed message and take the second repo's name.
I put the logging in a separate commit in case it wasn't wanted.
https://bugzilla.mozilla.org/show_bug.cgi?id=1450986
=> Handle transposed repo names in merge commit messages

gui/mozregui/wizard.py
Fixes the following backtrace when running the bisection or single build wizards:
```
Traceback (most recent call last):
File "/home/rm/src/mozregression/gui/mozregui/mainwindow.py", line 121, in single_run
self._start_runner(SingleRunWizard, self.single_runner)
File "/home/rm/src/mozregression/gui/mozregui/mainwindow.py", line 99, in _start_runner
wizard = wizard_class(self)
File "/home/rm/src/mozregression/gui/mozregui/wizard.py", line 309, in __init__
parent=parent)
File "/home/rm/src/mozregression/gui/mozregui/wizard.py", line 257, in __init__
"currentIndexChanged")
TypeError: setDefaultProperty(self, str, str, QT_SIGNAL): argument 3 has unexpected type 'str'
```
=> gui: fixup signal connection in wizards

mozregression/launchers.py
Can no longer disable updates completely via preferences
(https://bugzilla.mozilla.org/show_bug.cgi?id=1420514), so let's disable
automatically updating.
=> Adapt to changes in app update policy

mozregression/launchers.py, setup.py
Based on an earlier patch by bc <bob@bclary.com>
=> Bug 1484607 - Use mozdevice adb's new `require_root` parameter

setup.py
This version should pass the --wait-for-browser option
=> Bug 1494398 - Bump version of mozrunner

mozregression/cli.py, tests/unit/test_cli.py
I do this all the time and the silent-drop behaviour of mozregression is kinda annoying
=> Warn on using = instead of : in pref argument

gui/mozregui/build_runner.py, gui/setup.cfg, mozregression/main.py, tests/unit/test_main.py
Once Bug 1455707 lands (planned for Jan 30th), running an older build on a profile is going to essentially bail out. This passes the necessary command line argument to bypass that in the case where every test run uses the same profile.
I'm afraid I haven't been able to run the GUI tests because they don't seem to work for me for some reason.
=> Bug 1464127: Bypass profile downgrade detection when using the same profile for bisection.

mozregression/cli.py, mozregression/config.py, mozregression/launchers.py, mozregression/main.py, tests/unit/test_main.py
On some devices apparently the first-attempted path of
/storage/sdcard0/tests works to create the profile, but then the profile
is not readable from the app being tested (e.g. GVE). This patch allows
the user to override the default path to one that may work better.
=> Bug 1533517 - Allow the user to specify a path for profile storage on android

gui/README.rst
Riverbank Computing no longer serves PyQt4 installers for Windows:
"Binary installers for Windows are no longer provided."
Closes #xxxx
=> gui/README.rst: Update PyQt4 links for Windows

gui/mozregui/wizard.py, gui/tests/test_build_runner.py, mozregression/cli.py, mozregression/fetch_configs.py, setup.py, tests/unit/test_build_info.py, tests/unit/test_build_range.py, tests/unit/test_cli.py, tests/unit/test_fetch_build_info.py, tests/unit/test_fetch_configs.py
Doing this to hopefully get a build for testing.
=> Bug 1536013 - Select win64-aarch64 builds when appropriate.

mozregression/fetch_configs.py, tests/unit/test_fetch_configs.py
The previous code was incorrectly checking build_types for a `win64-aarch6464`
platform, which obviously doesn't exist.  Fortunately it doesn't matter at the
moment since win64-aarch64 isn't specified for any of the limited build types.
While this could have been fixed by just trimming the 64 off the end of the
substituted `os` string value (and switching the os check for the bits check),
switching to an explicit suffix should hopefully make it clearer what is
happening.
=> Correct error in aarch64 code in available_build_types

mozregression/branches.py
Sorry, but I couldn't build this myself on my windows machine, but I believe this single line change is enough to add comm-central repository to the list of branches. It is also maybe time to remove mozilla-aurora and comm-aurora from the release branches, because they are out of use since May 2017.
=> Add comm-central to branches

gui/mozregui/ui/intro.ui, mozregression/branches.py, mozregression/cli.py, mozregression/fetch_configs.py, mozregression/releases.py, tests/unit/test_branches.py, tests/unit/test_cli.py, tests/unit/test_releases.py
This should help with a number of ergonomic defects around the use of version numbers as build identifiers, and fixes a few different bugs: [bug 1308031](https://bugzilla.mozilla.org/show_bug.cgi?id=1308031), [bug 1494051](https://bugzilla.mozilla.org/show_bug.cgi?id=1494051), and [bug 1425164](https://bugzilla.mozilla.org/show_bug.cgi?id=1425164).
=> Improve support for version numbers on release repos

mozregression/fetch_build_info.py
Previously when mozregression failed to find any builds for a revision (because
of build failures, or in this case builds not yet being complete) after doing
route fallback it would print a log message about failing to find build info at
the final route it tried (pgo).
This caused actual confusion for a user who thought GUI had ignored the choice
of shippable. Log the original requested route instead.
=> Don't expose fallback routes in warning-level logs.

gui/mozregui/ui/build_selection.ui
Since the checkbox changes the labels and meaning of the fields it is confusing
to have it come after, since it could invalidate data the user already entered.
=> Bug 1508061 - Move find fix checkbox above the build selection fields

gui/mozregui/build_runner.py, gui/mozregui/ui/intro.ui, gui/mozregui/wizard.py
Useful when needing to run a test with a specific site
I punted on generic arg in GUI support, since just a URL should cover most use cases.
=> Bug 1422606 - Add support for opening app to a specific URL from GUI

requirements-dev.txt, setup.py
This should give us deterministic builds, without being so restrictive
about what the user has installed.
=> Pin using requirements files

mozregression/network.py
=> Bug 1551284 - Use html.parser by default for beautifulsoup

mozregression/build_range.py, tests/unit/test_build_range.py
BuildRange's check_expand bails if it doesn't have enough builds to start with,
but it then filters out any invalid builds, which can reduce the amount below
the required threshold (2), and doesn't then check again. At that point
continuing will throw IndexErrors since it assumes there will be items at
indexes 0 and -1.
=> Bug 1567259 - Bail out of check_expand if not enough valid builds.

mozregression/fetch_build_info.py, tests/unit/test_fetch_build_info.py
The NightlyInfoFetcher._fetch_build_info_from_url() method constructs
a dict with at least one key, "build_url", that is passed back
to the caller. However it was possible under specific circumstances to
build a dict where the "build_url" key was missing, causing later parts
of the program to fail.
This code adds a check for the "build_url" key and raises a helpful
error if the key is missing.
=> Bug 1404520 - Raise a helpful error when missing required build info

mozregression/fetch_configs.py
Fix the regex used to find Linux ASAN build files.
=> Bug 1404520 - Fix the Linux ASAN build file regex

requirements-dev.txt
Implicitly bumps the used version of urllib to 1.25+.
=> Bump pinned version of requests to 2.22

mozregression/json_pushes.py, tests/unit/test_json_pushes.py
Currently if a push doesn't exist in a repo we look for it in, the 404 error results in a `MozRegressionError` exception, which is fatal. That means we're failing out if a push doesn't exist in any one of the repos we search, even if it does exist in another (for example, an autoland push that's been merged to central, but not yet back to inbound). So, change that exception to an `EmptyPushlogError`, which isn't fatal.
I'd expect this to be a pretty common problem now that merges to mozilla-inbound have been slowed down and commit access to it is being sharply limited.
=> Bug 1589881 - Don't fail if a pushlog URL 404's

mozregression/config.py, mozregression/fetch_build_info.py, mozregression/fetch_configs.py, tests/unit/test_fetch_build_info.py, tests/unit/test_fetch_configs.py
I have tested this in the following ways:
* tried to run a newer build on autoland, verified it downloads from firefox-ci-tc.services.mozilla.com: mozregression -d --launch 5d471a86dc2963fadc67d4d37e03e8674289dbec --repo autoland
* tried to run an older build on autoland, verified it downloads from taskcluster.net: mozregression -d --launch 6a21e61770a8668cddce4825f9199270c5de35fb --repo autoland
=> Bug 1596201 - Try both taskcluster archives when dowloading builds from autoland or inbound

mozregression/fetch_configs.py, mozregression/json_pushes.py, tests/unit/test_approx_persist.py, tests/unit/test_build_info.py, tests/unit/test_build_range.py, tests/unit/test_fetch_configs.py, tests/unit/test_json_pushes.py
In some cases (e.g. bisecting GeckoView apps) we would attempt
to find builds on "mozilla-inbound" by default, which is now
discontinued.
=> Bug 1606902 - Set default integration branch to autoland

requirements/base.txt
This was attempting to work around a bug with a very old version
of python2, no need for it now that we're on python 3.5+.
=> Just use default requests, not requests[security]

gui/gui.spec
Glean and several related dependencies need some specific logic
to track their data files so they would be picked up by pyinstaller
=> Fix Glean pyinstaller packaging

gui/mozregui/build_runner.py
By default it would open the browser to `file:///`
=> Fix launching with no URL in Mac GUI

gui/tests/__init__.py, gui/tests/test_build_runner.py
Move to using pyqt's qtbot fixture instead of a hand-rolled
wait function
=> Attempt to fix an intermittent failure in GUI tests

gui/mozregui/ui/intro.ui, gui/mozregui/wizard.py, mozregression/cli.py, mozregression/fetch_configs.py
I just cobbled this together quickly as a minimum viable thing for what I needed. Happy to clean it up as you see fit. I only saw the PR in #565 after I wrote and was kind of surprised at how similar they were, but that one seems more complicated. Also the problem with using `mozinfo.processor` as the default is that it seems to be based on the host machine which we don't really care about so much for Android. My PR keeps the `arch` separate from `processor`.
=> Bug 1437591 - Add support for x86_64 GVE builds

mozregression/download_manager.py
In python2 the `values()` call here would have returned a list directly, but in
python3 it returns a live dict_values iterator, so if a download happens to
complete during this loop the other thread will remove it from the dict, causing
a "RuntimeError: dictionary changed size during iteration".
=> Bug 1637164 - Iterate over a list rather than a live dict view.

tests/unit/test_build_range.py, tests/unit/test_fetch_build_info.py, tests/unit/test_main.py
These were introduced in f6f16683ebb8 since the month and date numbers were
zero-padded for alignment in Python 2, but it's invalid syntax in 3.
=> Remove some unnecessary octals modernize introduced

gui/mozregui/main.py, mozregression/log.py
This is handy for debugging what Glean and other low-level libraries
used by mozregression are doing.
=> Redirect python logging in debug mode

gui/mozregui/skip_chooser.py
Since it leads to an AssertionError[0] when OK is clicked to confirm the
selection, or if the bound was double clicked to do so.
[0] `assert len(items) == 1` in `choose_next_build()`
=> Bug 1248212 - Don't allow clicking on bounds in the skip chooser window

mozregression/build_info.py, mozregression/fetch_configs.py, tests/unit/test_build_info.py
This prevents architecture mismatches when installing a persisted APK.
=> Bug 1651760 - Save GVE architecture in persisted filename

docs/glean/metrics.md, gui/mozregui/bisection.py, gui/mozregui/build_runner.py, mozregression/main.py, mozregression/metrics.yaml, mozregression/telemetry.py, tests/unit/test_main.py
This will tell us the usage patterns of mozregression, which
helps inform what types of builds we need to keep around. Specifically,
track:
* build_type (e.g. shippable, opt, etc.)
* bisection/launch dates (if specified)
=> Bug 1651401 - Add additional metrics on what builds are being retrieved

mozregression/config.py, mozregression/fetch_build_info.py, mozregression/fetch_configs.py, tests/unit/test_fetch_build_info.py
This is effectively a manual/partial backout of
f5f7466dd14e4a4e863cbc061a38025d152f7d99
Not only has the old taskcluster been decommissioned and thus no longer returns
anything, but changes to taskcluster-urls in version 13.0.1 were leading to
mozregression terminating when it passed the old TC root URLs.
=> Bug 1655682 - Stop trying old taskcluster root URL

mozregression/cli.py, tests/unit/test_cli.py, tests/unit/test_main.py
We used to have some convoluted logic to pick the earliest possible
build, but this is silly default behaviour. Most of the time regressions
are relatively recent, if they're not people can always specify their
own date manually.
=> Set default "bad" date to one year ago

mozregression/fetch_configs.py, tests/unit/test_fetch_configs.py
* Remove fennec 2.3 support (the time when this was something we'd
want to test is long past)
* Allow GVE to have shippable builds, now that we have them (fallback
to opt if not there)
* Fix bug in fennec/gve fallback build selection
=> Bug 1659829 - Updates to GeckoViewExample / Fennec support

mozregression/fetch_build_info.py
In python 3.6, the %z format specifier does not match time
zone strings containing a colon, such as "+00:00".
We know the string will in practice always be "+00:00", so
just match that exactly.
=> Bug 1661607 - Tweak the workaround to work for python 3.6 as well

gui/mozregui/utils.py, gui/tests/test_utils.py
So that it doesn't construct changesets URLs with spaces and fail to find
builds, or fail to parse dates from buildids with trailing spaces.
=> Bug 1672831 - Strip whitespace from buildids and changesets in the GUI

.github/dependabot.yml
The config is almost the same as the auto-suggested one on dependabot.com, but
with the addition of the new `dependency-type: all` setting, which hopefully
will manage to update indirect dependencies as well and lead to less PRs
failing due to "ERROR: In --require-hashes mode, all requirements must have
their versions pinned with ==. These do not:".
Though I'm not clear if it will cope with new additions to the dependency
graph, which seem to be what's causing such errors.
=> Migrate to native Dependabot

mozregression/dates.py, mozregression/errors.py, tests/unit/test_cli.py
Don't terminate and dump a traceback.
This doesn't spot typos like 2020-003-01 that won't match the regex `re.compile(r"(\d{4})\-(\d{1,2})\-(\d{1,2})")`.  We could potentially loosen the regex, either to maybe `re.compile(r"(\d{3,5})\-(\d{1,3})\-(\d{1,3})")` or just use `\d+`.  However those at least never crashed, we just try to use them as a hash instead.
=> Bug 1680309 - Handle invalid dates better

.github/workflows/build.yml, requirements/build.txt, requirements/dev.in
Should fix current breakage and hopefully prevent it from happening in the future.
=> Add coveralls to requirements and pin to 3.1.0

.github/workflows/build.yml
Inconsistency in the way various Python commands are being run in different workflows and jobs on different platforms can cause unexpected behaviour. For example, on macOS when running build-and-test-mac-gui, the build step fails as it can not find the mozregression package that was installed in the previous step.
=> workflows: use virtual environment where possible (bug 1778539)

requirements/dev.in, requirements/requirements-3.10-Linux.txt, requirements/requirements-3.10-Windows.txt, requirements/requirements-3.10-macOS.txt, requirements/requirements-3.6-Linux.txt, requirements/requirements-3.7-Linux.txt, requirements/requirements-3.8-Linux.txt, requirements/requirements-3.9-Linux.txt, requirements/requirements-3.9-Windows.txt, requirements/requirements-3.9-macOS.txt
NOTE: this is the last version of pytest that supports Python 3.6.
=> requirements: upgrade pytest from 6.2.2 to 6.2.5 (bug 1783863)

mozregression/launchers.py, tests/unit/test_launchers.py
Certain builds are unsigned, and when running them on arm64, macOS will
instantly terminate those processes. This patch will sign the code
object with an "ad-hoc" signature if it is unsigned.
NOTE: only unsigned packages are resigned, since signed packages with an
invalid signature should be left as-is for the time being.
=> launchers: sign code object if not signed at all (bug 1767139)

mozregression/launchers.py
Although the `app.update.auto:false` and `app.update.enabled:false` preferences are set, these have no effect on recent versions of Thunderbird due to their removal in [Bug 1420514](https://bugzilla.mozilla.org/show_bug.cgi?id=1420514) (ported to TB in [Bug 1479289](https://bugzilla.mozilla.org/show_bug.cgi?id=1479289)).  The replacement policy mechanism of setting `policies.DisableAppUpdate:true` in `distribution/policies.json` was added to `FirefoxLauncher` in 68ece936, but was not added to `ThunderbirdLauncher`.  This PR applies the same change so that app updates are disabled for Thunderbird.
Thanks for considering,
Kevin
=> launchers: Disable TB update by policy (bug 1783694)

requirements/requirements-3.10-Linux.txt, requirements/requirements-3.10-Windows.txt, requirements/requirements-3.10-macOS.txt, requirements/requirements-3.7-Linux.txt, requirements/requirements-3.8-Linux.txt, requirements/requirements-3.9-Linux.txt, requirements/requirements-3.9-Windows.txt, requirements/requirements-3.9-macOS.txt
- upgrade certifi from 2022.6.15.1 to 2022.9.14
- upgrade idna from 3.3 to 3.4
- upgrade setuptools from 65.2.0 to 65.3.0
- upgrade yamllint from 1.27.1 to 1.28.0
=> requirements: upgrade various packages

.github/workflows/build.yml
- update build-and-test-linux-gui with os matrix
=> workflows: add ubuntu 22.04 to linux tests (bug 1795878)

mozregression/launchers.py, tests/unit/test_launchers.py
- add check for invalid code signature if os is >= 13
=> launchers: handle invalid codesign on macOS 13 (bug 1781111)

mozregression/launchers.py
Do not use mozinfo.os_version.version any more as it was modified in a newer version of StringVersion. Instead, use string comparison directly.
=> launchers: compare strings directly in os_version (bug 1802616)

requirements/base.in, requirements/requirements-3.10-Linux.txt, requirements/requirements-3.10-Windows.txt, requirements/requirements-3.10-macOS.txt, requirements/requirements-3.11-Linux.txt, requirements/requirements-3.11-Windows.txt, requirements/requirements-3.11-macOS.txt, requirements/requirements-3.7-Linux.txt, requirements/requirements-3.8-Linux.txt, requirements/requirements-3.9-Linux.txt, requirements/requirements-3.9-Windows.txt, requirements/requirements-3.9-macOS.txt
glean-sdk 52.0.1 has a universal2 wheel which we can install in the virtual environment in order to build a universal2 bundle for mozregression-gui.
See https://github.com/pypa/pip/issues/11573 for more information on why the package has to be pinned in this way in the macOS requirements.
=> requirements: update minimum glean-sdk version (bug 1810534)

mozregression/log.py
As of PyInstaller 5.7.0, sys.stdout is changed from NullWriter to None
for GUI applications on Windows.
=> log: set ALLOW_COLOR to False if not sys.stdout (bug 1811930)

requirements/requirements-3.10-Linux.txt, requirements/requirements-3.10-Windows.txt, requirements/requirements-3.10-macOS.txt, requirements/requirements-3.11-Linux.txt, requirements/requirements-3.11-Windows.txt, requirements/requirements-3.11-macOS.txt, requirements/requirements-3.7-Linux.txt, requirements/requirements-3.8-Linux.txt, requirements/requirements-3.9-Linux.txt, requirements/requirements-3.9-Windows.txt, requirements/requirements-3.9-macOS.txt
Upgraded:
- pathspec upgraded from 0.10.3 to 0.11.0
- isort upgraded from 5.11.4 to 5.11.5
- setuptools upgraded from 65.7.0 to 67.0.0
- zipp upgraded from 3.11.0 to 3.12.0
=> requirements: update various packages

requirements/base.in, requirements/dev.in, requirements/gui-dev.in, requirements/linters.in, requirements/requirements-3.10-Linux.txt, requirements/requirements-3.10-Windows.txt, requirements/requirements-3.10-macOS.txt, requirements/requirements-3.11-Linux.txt, requirements/requirements-3.11-Windows.txt, requirements/requirements-3.11-macOS.txt, requirements/requirements-3.7-Linux.txt, requirements/requirements-3.8-Linux.txt, requirements/requirements-3.9-Linux.txt, requirements/requirements-3.9-Windows.txt, requirements/requirements-3.9-macOS.txt, tests/unit/test_launchers.py
Upgraded:
- beautifulsoup4 upgraded from 4.11.1 to 4.11.2
- black upgraded from 22.12.0 to 23.1.0
- configobj upgraded from 5.0.6 to 5.0.8
- flake8 upgraded from 5.0.4 to 6.0.0
- glean-parser upgraded from 6.4.0 to 7.0.0
- glean-sdk upgraded from 52.0.1 to 52.2.0
- importlib-metadata upgraded from 4.2.0 to 4.2.0
- mozfile upgraded from 2.1.0 to 3.0.0
- mozlog upgraded from 7.1.0 to 7.1.1
- pytest upgraded from 7.1.3 to 7.2.1
- pytest-qt upgraded from 4.1.0 to 4.2.0
- setuptools upgraded from 67.0.0 to 67.1.0
- taskcluster upgraded from 44.21.0 to 47.0.3
Added or removed:
- ansicon (1.89.0) added or removed
- blessed (1.19.1) added or removed
- blessings (1.7) added or removed
- exceptiongroup (1.1.0) added or removed
- jinxed (1.2.0) added or removed
- py (1.11.0) added or removed
- …
=> requirements: upgrade various requirements

mozregression/launchers.py
Move common functionality to `MozRunnerLauncher` and call it in both `FirefoxLauncher` and `ThunderbirdLauncher`.
=> launchers: handle invalid codesign on macOS 13 (bug 1817001)

.github/workflows/compile-requirements.yml, .github/workflows/run-compile-requirements.yml
Previously, jobs were run in series to avoid two or more jobs pushing at the same time. This can be handled by rebasing until a push is successful while running jobs in parallel, saving a significant amount of time.
=> workflows: run compile jobs in parallel (bug 1810224)

gui/mozregui/bisection.py, gui/mozregui/build_runner.py, gui/mozregui/check_release.py, gui/mozregui/crash_reporter.py, gui/mozregui/single_runner.py
See: https://bugreports.qt.io/browse/PYSIDE-2304 and https://bugreports.qt.io/browse/PYSIDE-1564. For relevant release/dev notes: https://www.qt.io/blog/qt-for-python-6.5 and https://wiki.qt.io/Qt_for_Python_Development_Notes#20._April_2023.
This only affects classes with multiple base classes.
=> gui: update __init__ to use super() (bug 1836097)

mozregression/telemetry.py
The original implementation was using the wrong string comparison to determine if the user is running Windows. This PR fixes this. See [mozinfo.py](https://searchfox.org/mozilla-central/source/testing/mozbase/mozinfo/mozinfo/mozinfo.py#87).
=> telemetry: fix windows string comparison in mozinfo (bug 1838490)

mozregression/fetch_build_info.py, tests/unit/test_fetch_build_info.py
- do a HEAD request to check if GVE artifacts are available from taskcluster
- raise a `BuildInfoNotFound` error when artifacts are no longer available
=> build_range: skip TC builds that have expired artifacts (bug 1841685)

setup.py
Python 3.6 was dropped in #1083.
=> setup: update programming language classifiers (bug 1843854)

.github/workflows/build.yml, tests/unit/test_launchers.py
- add new build-and-test-windows-cli job (bug 1844111)
- skip test that fails on windows (bug 1844111)
- add Python 3.11 to test matrix (bug 1843853)
=> workflows: add Python 3.11, Windows CLI tests to CI

docs/install.md
Remove documentation stating that users must override Gatekeeper on macOS.
=> docs: update macOS installation instructions (bug 1810744)

.github/workflows/upload-gui-to-workflow.yml
This is a new workflow in order to build artifacts without requiring a release tag. This will reduce the noise (i.e., dev releases) when testing changes that require full builds. Currently set to build any tag that starts with `build-`. It is left up to the tag author to delete tags that are no longer needed.
=> workflows: add push tag workflow to upload artifacts (bug 1849402)

.github/workflows/build.yml, .github/workflows/compile-requirements.yml, .github/workflows/deploy-gui.yml, .github/workflows/deploy.yml
These workflows use a deprecated version of node and should be upgraded.
=> workflows: upgrade checkout and setup-python (bug 1849643)

.github/workflows/deploy-gui.yml, .github/workflows/upload-gui-to-workflow.yml
This missing library causes a Qt platform plugin error since it does not get copied over when the app is being bundled. Upgrade Python while we're at it.
=> workflows: add missing libraries for Ubuntu builds (bug 1828122)

gui/gui.spec
Prior to this change, the splash hook will run on all platforms. It should only run on macOS.
=> splash_hook: run hook only on darwin (bug 1851916)

docs/_data/mozregression_supported_apps.yml, mozregression/cli.py, mozregression/fetch_configs.py, mozregression/launchers.py, tests/unit/test_fetch_configs.py, tests/unit/test_launchers.py
- add "fenix" as an app option in the cli
- update available arch options to include newer ones
- Add FenixNightlyConfigMixin and FenixConfig classes
- create new helper method `AndroidBrowser.launch_browser`
- move `adb.launch_fennec` calls to `adb.launch_application`
- create FenixLauncher class
- parametrize existing Fennec tests and update to support Fenix
- update cli help text
- add fenix as supported app in docs
=> fetch_configs, launchers: add Fenix nightlies support (bug 1556042)

mozregression/cli.py, mozregression/fetch_configs.py, mozregression/launchers.py, tests/unit/test_fetch_configs.py, tests/unit/test_launchers.py
- add "focus" as an app option
- add FocusNightlyConfigMixin and FocusConfig classes
- add FocusLauncher class
- add "fenix" to parametrized tests
=> fetch_configs, launchers: add Focus nightlies support (bug 1852620)

gui/mozregui/build_runner.py, gui/mozregui/wizard.py, mozregression/cli.py, mozregression/fetch_configs.py, tests/unit/test_fetch_configs.py
- add support for thunderbird-l10n
- limit date range to when builds became available
- add tests
=> fetch_configs, launchers: add thunderbird-l10n support (bug 1760826)

mozregression/launchers.py, tests/unit/test_launchers.py
- add support for URL arg to be passed to the browser
- add tests
=> launchers: pass URL arg to Android launchers (bug 1852787)

gui/gui.spec
After the most recent package upgrades various imports are no longer detected by PyInstaller. This PR updates the list to include those missing packages.
=> gui: update hidden imports (bug 1856652)

mozregression/cli.py
Without this parameter, the user will get a misleading "unable to find build info" error.
=> cli: require --arch parameter for fenix and focus (bug 1856952)

mozregression/fetch_configs.py
This was in the correct order for `ThunderbirdL10nConfig`, however this was not the case for `FirefoxL10nConfig`. This PR fixes this problem, ensuring that the definition for the build regex is defined correctly.
Edit: also move `CommonConfig` to the right in `ThunderbirdL10nConfig`, since `ThunderbirdL10nNightlyConfigMixin` may have been overridden in that case as well.
=> fetch_configs: fix MRO in FirefoxL10nConfig (bug 1874400)

.github/workflows/deploy-gui.yml, bin/virustotal-scan.py
Add VirusTotal scan script and job in workflow.
=> workflows: add virus scan check (bug 1881777)

mozregression/telemetry.py, setup.py
[importlib.resources.files](https://docs.python.org/3/library/importlib.resources.html#importlib.resources.files) behaves differently across different versions of Python, is not available in Python 3.8 (which is still supported at this time) and the `importlib_resources` package bridges those differences.
Since this bug fixes Python 3.12 support, also add this to the list of classifiers.
=> telemetry: use importlib_resources instead of pkg_resources (bug 1894839)

.github/workflows/deploy-gui.yml
- update Python version to 3.12.4
- fix macOS runner version to 13
This should have been done as part of https://github.com/mozilla/mozregression/pull/1690/files#diff-5c3fa597431eda03ac3339ae6bf7f05e1a50d6fc7333679ec38e21b337cb6721.
=>  workflows: fix macOS gui builds to match test runner (bug 1902706)

.github/workflows/deploy-gui.yml
Another missed change to line up with the previous updates to the test workflow.
In the future, we should somehow consolidate the common aspects of these configurations into a central place or import them from elsewhere, since changes to `deploy-gui.yml` do not get tested as part of the usual CI, and only as part of deployments.
=> workflows: fix outdated/hardcoded requirements file (bug 1902706)

.github/workflows/build.yml
- add ubuntu-24.04 to test matrix
- exclude Python 3.8 from the Ubuntu 24.04 run as it is not available
=> workflows: add Ubuntu 24.04 to test matrix (bug 1903562)

gui/build.py, mozregression/main.py
Python 3.13 removed the already deprecated "pipes" module from the standard library.
Some files were using the "quote" function from pipes, which prior to 3.13 was a re-export of a function with the same name in "shlex".
This change imports the shlex module directly.
https://github.com/python/cpython/blob/3.12/Lib/pipes.py#L66 https://docs.python.org/3/whatsnew/3.13.html
=> gui: replace usage of stdlib pipes library with shlex (bug 1914478)

.github/workflows/build.yml
- remove ubuntu-20.04 from build-and-test-linux-base
- also add ubuntu-24.04 to build-and-test-linux-gui
NOTE: lint issues will be fixed in #2018
=> workflows: deprecate ubuntu-20.04 from workflow jobs (bug 1980503)
